### ISSUE TITLE
Add a custom font using google_fonts package

### ISSUE THREAD

**Issue by aayushbisen** [aayushbisen/Clima#4]
Use the [google_fonts](https://pub.dev/packages/google_fonts) to change the custom font to [Inter](https://fonts.google.com/specimen/Inter) in the whole project.

Let me know if you need any help!

Good luck ✨

**Comment by nikeight** [comment]
Hey @aayushbisen 
This looks like a good first issue that I can take and contribute to the project. 
Can you please assign it to me?

**Comment by aayushbisen** [comment]
Sure @nikeight you can work on this.

**Comment by aayushbisen** [comment]
Closed with #5
